framework:
    messenger:
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    topic:
                        name: customers
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed_customer: 'doctrine://default?queue_name=failed'

            # async_producer:
            #     dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            #     options:
            #         topic:
            #             name: producers
            #     retry_strategy:
            #         max_retries: 3
            #         multiplier: 2
            # failed_producer: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Message\KafkaMessage: async
