framework:
    messenger:
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            customers: '%env(MESSENGER_TRANSPORT_DSN_CUSTOMERS)%'
            products: '%env(MESSENGER_TRANSPORT_DSN_PRODUCTS)%'

        routing:
            # Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            # Symfony\Component\Notifier\Message\ChatMessage: async
            # Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            App\Message\CustomersMessage: customers
            App\Message\ProductsMessage: products
