version: '3'

services:
  rentalapp:
    build: .
    container_name: rentalapp
    volumes:
      - ./:/var/www
    depends_on:
      - rentalapp-database
      - rentalapp-redis

###> doctrine/doctrine-bundle ###
  rentalapp-database:
    container_name: rentalapp-database
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - ./.docker/db_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  rentalapp-nginx:
      build: ./.docker/nginx
      restart: always
      ports: 
        - "8000:80"
      volumes:
        - ./:/var/www
      depends_on:
        - rentalapp

  rentalapp-redis:
    image: redis:alpine
    expose:
      - 6380

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###networks:

networks:
  default:
    external:
      name: jornada-network
